### ISSUE TITLE
Theme selection

### ISSUE THREAD

**Issue by SirWindfield** [bobbylight/RText#3]
Changing the theme in RText is quiet painful. RSTA already ships with some nice themes,, but RText does not provide any way to use them, expect for manually change every color for every single token type. A button like "Import" would be fine, maybe also a button for exporting the current selfmade theme.

**Comment by bobbylight** [comment]
There is now a "Theme" panel in the Options dialog that allows users to select from a few canned themes:

* Default (System LAF, RSTA default colors)
* Eclipse (System LAF, Eclipse editor colors)
* Dark (Darcula LAF, "dark" RSTA theme colors)
* Monokai (Darcula LAF, "monokai" RSTA theme colors)

As you can see, a "theme," from the perspective of this Options dialog panel, is a Look and Feel + an RSTA theme (plus a few other color tweaks to other places in the UI, described below).  The idea is that you can select a theme from this panel, then tweak any individual RSTA colors to your liking if desired.

I should note that switching between "themes" in this option panel also changes a few other colors in the UI, depending on whether a "dark" or a "light" theme is selected ("dark" or "light" referring to the overall color scheme of the LAF).  This is because dark LAFs typically need lighter colors in components, especially for fonts, to be readable.  Other colors tweaked via themes include:

* "Modified file" color in tab names
* Input, stdout, stderr colors in the Console panel

With all of this finally in place, I'm closing this ticket.
