### ISSUE TITLE
خطاء القراءة والكتابة في اللغة العربية Error , Arabic reading and writing from right to left

### ISSUE THREAD

**Issue by thamermousa** [bobbylight/RText#53]
Error , Arabic reading and writing from right to left

As in the picture
![2021-01-26_045143](https://user-images.githubusercontent.com/3912594/105794808-72c14780-5f94-11eb-98ea-2b4edbe1c218.jpg)

please solve the problem

I liked the program, especially because it is translated into Arabic

Thank you

**Comment by bobbylight** [comment]
Thanks for the feedback!  The issue is that the the code editor component used, `RSyntaxTextArea`, doesn't properly support right-to-left rendering (not a priority since it's a code editor).  Could you please create a feature request there?  I don't know how long it would take to get implemented but at least then it would be tracked:

https://github.com/bobbylight/RSyntaxTextArea
